apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: acpsec
spec:
  replicas: 1
  template:
    metadata:
      labels:
        api: acpsec
    spec:
      containers:
      - name: acpsec
        image: <<image-tag>>
        env:
        - name: GEO_KEY
          value: AIzaSyDr3iN4ZiOdk_X3t8Wx1s_Y6rvqxQUnsWI
        - name: GEO_DIR_KEY
          value: AIzaSyDp7yLyid5qJOIgQo1d_gt11NBBGCJivFA
        - name: GEO_APP_TITLE
          value: 'Public Banking'
        - name: GEO_TITLE
          value: 'Driving on '
        - name: GEO_PLACEHOLDER
          value: 'Enter Branch Name... '
        - name: CASH_LIMIT
          value: '300'
        ports:
        - containerPort: 8077
        args:
        - node
        - server.js